nas-identifier my-nas-id
authserver 192.168.211.130:1812
acctserver 192.168.211.130:1813
servers /home/yrb/src/cleveldb/conf/servers
dictionary /home/yrb/src/cleveldb/conf/dictionary
radius_timeout 10
radius_retries 3
bindaddr *
# To enable verbose debugging messages in syslog, enable the following
clientdebug 1